language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-28.0.3
    - android-14
before_install:
  - yes | sdkmanager "platforms;android-14"
script:
   - cd ./android-timetracker
   - ./gradlew build connectedCheck
